BW\BlogBundle\Entity\Category:
    type: entity
    repositoryClass: Gedmo\Tree\Entity\Repository\NestedTreeRepository
    table: categories
    gedmo:
        tree:
            type: nested
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        heading:
            type: string
            length: 255
        slug:
            type: string
            length: 255
        title:
            type: string
            length: 255
        metaDescription:
            type: string
            length: 255
        shortDescription:
            column: short_description
            type: text
        description:
            type: text
        published:
            type: boolean
        created:
            type: datetime
        updated:
            type: datetime
        order:
            column: ordering
            type: integer
        # Nested Set
        root:
            type: integer
            nullable: true
            gedmo:
                - treeRoot
        level:
            column: lvl
            type: integer
            gedmo:
                - treeLevel
        left:
            column: lft
            type: integer
            gedmo:
                - treeLeft
        right:
            column: rgt
            type: integer
            gedmo:
                - treeRight
    oneToOne:
        image:
            targetEntity: BW\UploadBundle\Entity\Image
            cascade: [persist, remove]
    oneToMany:
        children:
            targetEntity: BW\BlogBundle\Entity\Category
            mappedBy: parent
            orderBy:
                left: ASC
        posts:
            targetEntity: BW\BlogBundle\Entity\Post
            mappedBy: category
    manyToOne:
        parent:
            targetEntity: BW\BlogBundle\Entity\Category
            inversedBy: children
            joinColumn:
                #name: parent_id
                #referencedColumnName: id
                onDelete: CASCADE
            gedmo:
                - treeParent
        route:
            targetEntity: BW\RouterBundle\Entity\Route
            cascade: [persist, remove]
    lifecycleCallbacks:
        prePersist: [generateLevel]
        preUpdate: [generateLevel, generateUpdatedDate]
