parameters:
#    bw_router.example.class: BW\RouterBundle\Example

services:
#    bw_router.example:
#        class: %bw_router.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]

    bw_router.event_listener.kernel_request:
        class: BW\RouterBundle\EventListener\KernelRequestListener
        arguments: ["@request_stack", "@doctrine.orm.entity_manager", "@router", "@logger"]
        tags:
            - { name: kernel.event_listener, event: kernel.request, method: onKernelRequest, priority: 64 }
