parameters:
#    bw_module.example.class: BW\ModuleBundle\Example

services:
#    bw_module.example:
#        class: %bw_module.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]

    bw_module.service.position:
        class: BW\ModuleBundle\Service\PositionService
        arguments: ["@doctrine.orm.entity_manager", "@twig", "@bw_router.event_listener.database_route_loading"]

    bw_module.service.widget:
        class: BW\ModuleBundle\Service\WidgetService
        arguments: ["@doctrine.orm.entity_manager", "@twig"]