parameters:
#    bw_module.example.class: BW\ModuleBundle\Example

services:
#    bw_module.example:
#        class: %bw_module.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]

    bw_module.service.position:
        class: BW\ModuleBundle\Service\PositionService
        arguments: ["@service_container"]

    bw_module.service.widget:
        class: BW\ModuleBundle\Service\WidgetService
        arguments: ["@doctrine.orm.entity_manager", "@twig", "@logger"]

    bw_module.service.custom_widget:
        class: BW\ModuleBundle\Service\CustomWidgetService
        arguments: ["@twig", "@logger"]