parameters:
#    bw_module.example.class: BW\ModuleBundle\Example

services:
#    bw_module.example:
#        class: %bw_module.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
