parameters:
#    bw_module.example.class: BW\ModuleBundle\Example

services:
#    bw_module.example:
#        class: %bw_module.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]

    bw_module.service.position:
        class: BW\ModuleBundle\Service\PositionService
        arguments: ["@service_container"]

    bw_module.service.widget:
        class: BW\ModuleBundle\Service\WidgetService
        arguments: ["@doctrine.orm.entity_manager", "@logger"]

    bw_module.service.html_widget:
        class: BW\ModuleBundle\Service\HtmlWidgetService
        arguments: ["@twig", "@logger"]

    bw_module.service.feedback_form_widget:
        class: BW\ModuleBundle\Service\FeedbackFormWidgetService
        arguments: ["@request_stack", "@form.factory", "@router", "@twig", "@logger"]
