bw_breadcrumbs:
    resource: "@BWBreadcrumbsBundle/Resources/config/routing.yml"
    prefix:   /

bw_upload:
    resource: "@BWUploadBundle/Resources/config/routing.yml"
    prefix:   /

bw_menu:
    resource: "@BWMenuBundle/Resources/config/routing.yml"
    prefix:   /

bw_user:
    resource: "@BWUserBundle/Resources/config/routing.yml"
    prefix:   /

bw_module:
    resource: "@BWModuleBundle/Resources/config/routing.yml"
    prefix:   /

bw_skeleton:
    resource: "@BWSkeletonBundle/Resources/config/routing.yml"
    prefix:   /

bw_blog:
    resource: "@BWBlogBundle/Resources/config/routing.yml"
    prefix:   /

_liip_imagine:
    resource: "@LiipImagineBundle/Resources/config/routing.xml"

bw_router:
    resource: "@BWRouterBundle/Resources/config/routing.yml"
    prefix:   /

app:
    resource: "@AppBundle/Resources/config/routing.yml"
    prefix:   /
