security:
    encoders:
#        Symfony\Component\Security\Core\User\User: plaintext
        BW\UserBundle\Entity\User:
            algorithm:        sha1
            iterations:       5
            encode_as_base64: false

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    providers:
#        in_memory:
#            memory:
#                users:
#                    user:  { password: userpass, roles: [ 'ROLE_USER' ] }
#                    admin: { password: adminpass, roles: [ 'ROLE_ADMIN' ] }
        in_database:
            entity:
                class: BW\UserBundle\Entity\User
#                property: username
#                manager_name: user

    firewalls:
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false
#        demo_login:
#            pattern:  ^/demo/secured/login$
#            security: false
#        demo_secured_area:
#            pattern:    ^/demo/secured/
#            form_login:
#                check_path: _demo_security_check
#                login_path: _demo_login
#            logout:
#                path:   _demo_logout
#                target: _demo
#            #anonymous: ~
#            #http_basic:
#            #    realm: "Secured Demo Area"
        auth:
            pattern:    ^/
            anonymous:  ~
            form_login:
                login_path: user_sign_in
                check_path: user_sign_in_check
            logout:
                path:   user_sign_out
#                target: home

    access_control:
        #- { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY, requires_channel: https }
        - { path: user_sign_in, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/_admin, roles: ROLE_ADMIN }
