parameters:
#    bw_default.example.class: BW\DefaultBundle\Example
    bw_default.service.transliterating.alphabet_overridden: {"–ê": "A"}
    bw_default.event_listener.sluggable.denied_characters: '*[^#/0-9A-Za-z_-]*'
    bw_default.event_listener.sluggable.to_lower: true

services:
#    bw_default.example:
#        class: %bw_default.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]

    bw_default.twig.bw_extension:
        class: BW\DefaultBundle\Twig\BWExtension
        arguments: ["@service_container", "@logger"]
        tags:
            - { name: twig.extension }

    bw_default.service.nested_set:
        class: BW\DefaultBundle\Service\NestedSet
        arguments: ["@doctrine.orm.entity_manager", "@logger"]

    bw_default.service.transliterating:
        class: BW\DefaultBundle\Service\TransliteratingService
        arguments: ["%bw_default.service.transliterating.alphabet_overridden%"]

    bw_default.event_listener.sluggable:
        class: BW\DefaultBundle\EventListener\SluggableEventListener
        arguments:
            - "@bw_default.service.transliterating"
            - "%bw_default.event_listener.sluggable.denied_characters%"
            - "%bw_default.event_listener.sluggable.to_lower%"
        tags:
            - { name: doctrine.event_listener, event: prePersist }
            - { name: doctrine.event_listener, event: preUpdate }
