BW\UserBundle\Entity\Role:
    type: entity
    table: roles
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        name:
            type: string
            length: 30
        role:
            type: string
            length: 20
            unique: true
    manyToMany:
        users:
            targetEntity: BW\UserBundle\Entity\User
            mappedBy: roles
    lifecycleCallbacks: {}
