BW\UserBundle\Entity\User:
    type: entity
    table: users
    repositoryClass: BW\UserBundle\Entity\UserRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        username:
            type: string
            length: 25
            unique: true
        password:
            type: string
            length: 40
        salt:
            type: string
            length: 32
        email:
            type: string
            length: 60
            unique: true
            nullable: true
        enabled:
            column: enabled
            type: boolean
        confirmed:
            column: confirmed
            type: boolean
        created:
            type: datetime
        updated:
            type: datetime
        hash:
            type: string
            length: 255
        facebookId:
            column: facebook_id
            type: string
            length: 32
            unique: true
            nullable: true
        googleId:
            column: google_id
            type: string
            length: 32
            unique: true
            nullable: true
        vkId:
            column: vk_id
            type: string
            length: 32
            unique: true
            nullable: true
    oneToOne:
        profile:
            targetEntity: BW\UserBundle\Entity\Profile
            mappedBy: user
    manyToMany:
        roles:
            targetEntity: BW\UserBundle\Entity\Role
            inversedBy: users
    lifecycleCallbacks:
        preUpdate: [generateUpdatedDate]
