parameters:
#    bw_upload.example.class: BW\UploadBundle\Example

services:
#    bw_upload.example:
#        class: %bw_upload.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]

    bw_upload.service.image_resizing:
        class: BW\UploadBundle\Service\ImageResizingService
        arguments: []

    bw_upload.twig.bw_extension:
        class: BW\UploadBundle\Twig\BWExtension
        arguments: ["@bw_upload.service.image_resizing", "@logger"]
        tags:
            - { name: twig.extension }
