BW\RouterBundle\Entity\Route:
    type: entity
    table: routes
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        path:
            type: string
            length: 255
            unique: true
        defaults:
            type: array
    lifecycleCallbacks: { }
