parameters:

services:
#    bw_breadcrumbs.example:
#        class: BW\BreadcrumbsBundle\Example
#        arguments: [@service_id, "plain_value", %parameter%]

    bw_breadcrumbs:
        class: BW\BreadcrumbsBundle\Service\BreadcrumbsService
        calls:
            - [setNavigation, ["%bw_breadcrumbs.navigation%"]]
            - [setShowFirst, ["%bw_breadcrumbs.show_first%"]]
            - [setShowLast, ["%bw_breadcrumbs.show_last%"]]
            - [setLastAsLink, ["%bw_breadcrumbs.last_as_link%"]]
            - [setShowSeparator, ["%bw_breadcrumbs.show_separator%"]]
            - [setSeparatorCharacter, ["%bw_breadcrumbs.separator_character%"]]

    bw_breadcrumbs.twig.bw_extension:
        class: BW\BreadcrumbsBundle\Twig\BWExtension
        arguments: ["@service_container"]
        tags:
            - { name: twig.extension }
