services:
#    bw_breadcrumbs.example:
#        class: BW\BreadcrumbsBundle\Example
#        arguments: [@service_id, "plain_value", %parameter%]

    bw_breadcrumb:
        class: BW\BreadcrumbsBundle\Service\BreadcrumbService
        arguments: []
