BW\ModuleBundle\Entity\FeedbackFormWidget:
    type: entity
    table: feedback_form_widgets
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        redirectUrl:
            type: string
            length: 255
        email:
            type: string
            length: 255
        subject:
            type: string
            length: 255
        fields:
            type: json_array
    oneToOne:
        widget:
            targetEntity: BW\ModuleBundle\Entity\Widget
            inversedBy: feedbackFormWidget
            cascade: [persist, remove]
    lifecycleCallbacks: {}
