BW\ModuleBundle\Entity\FeedbackFormWidget:
    type: entity
    table: feedback_form_widgets
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        redirectUrl:
            type: string
            length: 255
        emailTo:
            type: string
            length: 255
        messageSubject:
            type: string
            length: 255
        messageBody:
            type: text
        fields:
            type: json_array
    oneToOne:
        widget:
            targetEntity: BW\ModuleBundle\Entity\Widget
            inversedBy: feedbackFormWidget
            cascade: [persist, remove]
    lifecycleCallbacks: {}
