BW\ModuleBundle\Entity\Position:
    type: entity
    table: positions
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        name:
            type: string
            length: 255
        description:
            type: string
            length: 255
    oneToMany:
        widgets:
            targetEntity: BW\ModuleBundle\Entity\Widget
            mappedBy: position
            orderBy:
                order: ASC
    lifecycleCallbacks: {  }
