BW\ModuleBundle\Entity\Type:
    type: entity
    table: widget_types
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        name:
            type: string
            length: 255
        alias:
            type: string
            length: 255
        property:
            type: string
            length: 255
        formTypeClass:
            type: string
            length: 255
    oneToMany:
        widgets:
            targetEntity: BW\ModuleBundle\Entity\Widget
            mappedBy: type
    lifecycleCallbacks: {}
