BW\ModuleBundle\Entity\Type:
    type: entity
    table: widget_types
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        name:
            type: string
            length: 255
    lifecycleCallbacks: {}
