BW\ModuleBundle\Entity\Widget:
    type: entity
    table: widgets
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        heading:
            type: string
            length: 255
        shortDescription:
            type: string
            length: 255
        published:
            type: boolean
        order:
            column: ordering
            type: integer
        visibility:
            type: boolean
    oneToOne:
        customWidget:
            targetEntity: BW\ModuleBundle\Entity\CustomWidget
            mappedBy: widget
            cascade: [persist, remove]
        menuWidget:
            targetEntity: BW\MenuBundle\Entity\MenuWidget
            mappedBy: widget
            cascade: [persist, remove]
    oneToMany:
        widgetRoutes:
            targetEntity: BW\ModuleBundle\Entity\WidgetRoute
            mappedBy: widget
    manyToOne:
        type:
            targetEntity: BW\ModuleBundle\Entity\Type
            inversedBy: widgets
        position:
            targetEntity: BW\ModuleBundle\Entity\Position
            inversedBy: widgets
    lifecycleCallbacks: {}
