BW\ModuleBundle\Entity\Widget:
    type: entity
    table: widgets
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        heading:
            type: string
            length: 255
        description:
            type: text
        published:
            type: boolean
        order:
            column: ordering
            type: integer
    manyToOne:
        position:
            targetEntity: BW\ModuleBundle\Entity\Position
            inversedBy: widgets
    lifecycleCallbacks: {  }
