database:
    path:     /
    defaults: { _controller: BWDefaultBundle:Database:list }

database_dump:
    path:     /dump
    defaults: { _controller: BWDefaultBundle:Database:dump }
    requirements: { _method: post }

database_dump_delete:
    path:     /dump/{filename}/delete
    defaults: { _controller: BWDefaultBundle:Database:delete }

database_dump_delete_confirm:
    path:     /dump/{filename}/delete/confirm
    defaults: { _controller: BWDefaultBundle:Database:deleteConfirm }
    requirements: { _method: post|delete }
