BW\MenuBundle\Entity\Item:
    type: entity
    repositoryClass: Gedmo\Tree\Entity\Repository\NestedTreeRepository
    table: items
    gedmo:
        tree:
            type: nested
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        name:
            type: string
            length: 255
        uri:
            type: string
            length: 255
        title:
            type: string
            length: 255
        class:
            type: string
            length: 255
        published:
            type: boolean
        blank:
            type: boolean
        order:
            column: ordering
            type: integer
        # Nested Set
        root:
            type: integer
            nullable: true
            gedmo:
                - treeRoot
        level:
            column: lvl
            type: integer
            gedmo:
                - treeLevel
        left:
            column: lft
            type: integer
            gedmo:
                - treeLeft
        right:
            column: rgt
            type: integer
            gedmo:
                - treeRight
    oneToMany:
        children:
            targetEntity: BW\MenuBundle\Entity\Item
            mappedBy: parent
            orderBy:
                left: ASC
            cascade: [remove]
    manyToOne:
        parent:
            targetEntity: BW\MenuBundle\Entity\Item
            inversedBy: children
            joinColumn:
                #name: parent_id
                #referencedColumnName: id
                #onDelete: CASCADE
            gedmo:
                - treeParent
        menu:
            targetEntity: BW\MenuBundle\Entity\Menu
            inversedBy: items
        route:
            targetEntity: BW\RouterBundle\Entity\Route
    lifecycleCallbacks: {}
