bw_user_bundle_user:
    resource: "@BWUserBundle/Resources/config/routing/user_admin.yml"
    prefix:   /_admin/user

bw_user_bundle_role:
    resource: "@BWUserBundle/Resources/config/routing/role_admin.yml"
    prefix:   /_admin/role
